### PR TITLE
Escape underscores in Tox spec.

### PR DESCRIPTION
**Pull request by robinlinden**
The generated [spec](https://toktok.ltd/spec) is currently missing 433 underscores.

This change is [Reviewable](https://reviewable.io/reviews/toktok/hs-toxcore/123)

### CODE REVIEW

**Comment by iphydf** [comment]
Perhaps it's better to use `\verb!foo_bar!` instead of escaping all these underscores. This PR does not fix the `uint8_t` underscores in the tables (or does it? did you check?).

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/tox/Network/Tox.lhs, line 998 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/123#-Kc9oOrw018WC0zl-fmj:-Kc9oOrw018WC0zl-fmk:b-vnjhji) ([raw file](https://github.com/toktok/hs-toxcore/blob/87ac107847dc0838efeb9f2d8827e29220f3d77e/src/tox/Network/Tox.lhs#L998)):*
> ```lhaskell
> \begin{verbatim}
> Client:                                     Server:
> generate\_shared\_key(                        generate\_shared\_key(
> ```

No need for escapes in verbatim environments. There are several of these.

---

*[src/tox/Network/Tox.lhs, line 1405 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/123#-Kc9oVxPUFVJTV3Q7iWg:-Kc9oVxQowDCekjurZfQ:b-9exzux) ([raw file](https://github.com/toktok/hs-toxcore/blob/87ac107847dc0838efeb9f2d8827e29220f3d77e/src/tox/Network/Tox.lhs#L1405)):*
> ```lhaskell
> 
> \begin{verbatim}
> [uint32\_t nospam][Message (UTF8) 1 to ONION\_CLIENT\_MAX\_DATA\_SIZE bytes]
> ```

Remove superfluous \ from all verbatim environments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hs-toxcore/123#-:-Kc9opn-uE_fAK0tHZiP:bfqm54l)*

**Comment by robinlinden** [comment]
This does fix underscores for `uint8_t` in tables. (I checked.)
I wasn't sure about escaping underscores in verbatim blocks, but since they're omitted from the generated spec, I couldn't verify one way or another. (We should probably fix that.) 

Re: "Perhaps it's better to use \verb!foo_bar! instead of escaping all these underscores."
You might be right. Most suggestions I found for this were "Use the underscores package" or "Just escape them." Some people suggested inline verbs, but according to other people, that won't work in e.g. lists.

I made a gist of the spec [here](https://gist.github.com/robinlinden/e134057bf90f2eb0e848911c99eb97a4) if you want to have a look.

**Comment by robinlinden** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/tox/Network/Tox.lhs, line 998 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/123#-Kc9oOrw018WC0zl-fmj:-KcBOr0NnAeYGYpAF8c5:b-896fix) ([raw file](https://github.com/toktok/hs-toxcore/blob/87ac107847dc0838efeb9f2d8827e29220f3d77e/src/tox/Network/Tox.lhs#L998)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

No need for escapes in verbatim environments. There are several of these.
</blockquote></details>

Done.

---

*[src/tox/Network/Tox.lhs, line 1405 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/123#-Kc9oVxPUFVJTV3Q7iWg:-KcBOraspQ7dwyV5fh8P:b-gup4aj) ([raw file](https://github.com/toktok/hs-toxcore/blob/87ac107847dc0838efeb9f2d8827e29220f3d77e/src/tox/Network/Tox.lhs#L1405)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Remove superfluous \ from all verbatim environments.
</blockquote></details>

Done in all verbatim environments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hs-toxcore/123)*

**Comment by iphydf** [comment]
@robinlinden can you rebase?

**Comment by robinlinden** [comment]
Rebased.

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hs-toxcore/123#-:-KeUA4f0LHnO-hnSGgxk:b-jbsf8z)*

**Pull request merged**
