### PR TITLE
Use official markdown license for AGPLv3.

### PR DESCRIPTION
**Pull request by iphydf**
Taken from https://www.gnu.org/licenses/agpl-3.0.md

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/hs-toxcore/118)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hs-toxcore/118#-:-KaFMOBR58_o-FkG7VbC:b-jbsf8z)*

**Comment by GrayHatter** [comment]
While I know I don't get to decide. I'm not okay with AGPL for this repo, and likely won't contribute much code if it remains AGPL. (No real loss to be sure)

**Comment by piling** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hs-toxcore/118#-:-KaIfiDXjC5G2YxsatDX:b-jbsf8z)*

**Comment by fcore117** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hs-toxcore/118)*

**Pull request merged**
