### PR TITLE
Single data structure for a k-bucket and for a search entry list

### PR DESCRIPTION
**Pull request by zugz**
This change is [Reviewable](https://reviewable.io/reviews/toktok/hs-toxcore/121)

### CODE REVIEW

**Comment by iphydf** [comment]
Review status: 0 of 11 files reviewed at latest revision, 14 unresolved discussions.

---

*[src/testsuite/Network/Tox/DHT/ClientListSpec.hs, line 27 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7Ttmuiw5XA9pa0CpF:-Kb7Ttmuiw5XA9pa0CpG:b-9aq7mv) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/ClientListSpec.hs#L27)):*
> ```Haskell
>   it "has no more than maxSize elements" $
>     property $ \clientList ->
>         Map.size (ClientList.nodes clientList) `shouldSatisfy` (<= ClientList.maxSize clientList)
> ```

Indentation is 2 spaces. We can talk about changing that, but then we should change it everywhere at once, in a separate PR.

---

*[src/testsuite/Network/Tox/DHT/ClientListSpec.hs, line 57 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7TyyLC5EvPL4zbZHB:-Kb7TyyLC5EvPL4zbZHC:b-ixwb34) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/ClientListSpec.hs#L57)):*
> ```Haskell
>           sortNodes = sortBy $ comparing nodeDistance
>         in
>           take (ClientList.maxSize clientList) (sortNodes allNodes) `shouldBe` sortNodes keptNodes
> ```

Unindent by 2 spaces.

---

*[src/testsuite/Network/Tox/DHT/KBucketsSpec.hs, line 28 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7VJjpdQVVh4Nd8Pgw:-Kb7VJjpdQVVh4Nd8Pgx:b1wzuto) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/KBucketsSpec.hs#L28)):*
> ```Haskell
> 
> 
> getAllBuckets :: KBuckets -> [[NodeInfo.NodeInfo]]
> ```

Add `import Network.Tox.NodeInfo.NodeInfo (NodeInfo)`. Generally I've added unqualified imports for the type names and qualified imports for the modules.

---

*[src/testsuite/Network/Tox/DHT/KBucketsSpec.hs, line 72 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7WSOdEIHBY9W9jMKY:-Kb7WSOdEIHBY9W9jMKZ:b-owc0de) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/KBucketsSpec.hs#L72)):*
> ```Haskell
>       afterAdd0 `shouldBe` afterAdd1
> 
>   it "buckets have maximum size bucketSize" $
> ```

"it buckets have maximum size" isn't a sentence. I've been trying to keep these tests in the \*spec style with "describe foo: it does bleh, it has blah, it is bork". In this case, you're describing two properties of "buckets": they "have max.." and "have base key...".

---

*[src/testsuite/Network/Tox/DHT/KBucketsSpec.hs, line 74 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7WopHOxWuJcr-H4pU:-Kb7WopHOxWuJcr-H4pV:b-xvtcuk) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/KBucketsSpec.hs#L74)):*
> ```Haskell
>   it "buckets have maximum size bucketSize" $
>     property $ \kBuckets ->
>       mapM_ (`shouldSatisfy` (==KBuckets.bucketSize kBuckets) . ClientList.maxSize) $ Map.elems $ KBuckets.buckets kBuckets
> ```

Add space after `==`. I almost always avoid contracting token sequences. In this case, it hints that `==` and `KBuckets.bucketSize` are more tightly connected than the following `kBuckets`, while actually you're doing `(== (KBuckets.bucketSize kBuckets))`, making this contraction actively confusing.

---

*[src/testsuite/Network/Tox/DHT/KBucketsSpec.hs, line 78 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7XIba9QVdZ9jTPwzD:-Kb7XIba9QVdZ9jTPwzE:bpspmb2) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/KBucketsSpec.hs#L78)):*
> ```Haskell
>   it "buckets have base key baseKey" $
>     property $ \kBuckets ->
>       mapM_ (`shouldSatisfy` (==KBuckets.baseKey kBuckets) . ClientList.baseKey) $ Map.elems $ KBuckets.buckets kBuckets
> ```

I've switched from the `foo $ bar $ cow x` style to `foo . bar . cow $ x` style for two reasons:
1. It makes it clearer that we're applying a composition of functions to some value.
2. Factoring out that composition and giving it a name becomes a matter of just cut&paste instead of cut&paste and then replacing `$` with `.`.

In this particular case, as well as the previous and the next, changing it to composition rather than application also allows for eta-reduction, making it a beautiful `property $ some . function . composition`.

---

*[src/testsuite/Network/Tox/DHT/KBucketsSpec.hs, line 120 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7YSc2VUWK-D09rtN6:-Kb7YSc2VUWK-D09rtN7:b3x3o1o) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/KBucketsSpec.hs#L120)):*
> ```Haskell
>       property $ \kBuckets ->
>         let
>           nodes             = KBuckets.foldNodes (\ns n -> ns++[n]) [] kBuckets
> ```

I'm a bit unhappy about this `O(n^2)` algorithm. It's mine, but perhaps change it to `O(n)` if it doesn't become too ugly? Also in the other test you copied from this one.

---

*[src/tox/Network/Tox/DHT/ClientList.lhs, line 54 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7QSGfOPwcTW6L6L1q:-Kb7QSGfOPwcTW6L6L1r:b3dw8w9) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/ClientList.lhs#L54)):*
> ```lhaskell
>   { baseKey = publicKey
>   , maxSize = size
>   , nodes = Map.empty }
> ```

Align `=` and put `}` on a separate line (makes it easier to reorder bindings).

---

*[src/tox/Network/Tox/DHT/ClientList.lhs, line 101 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7QrpDYq3a84FVUcSk:-Kb7QrpDYq3a84FVUcSl:bvr9tx5) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/ClientList.lhs#L101)):*
> ```lhaskell
>     Map.delete $ Distance.xorDistance publicKey $ baseKey clientList
> 
> -- |mapTake is Data.Map.take in >=containers-0.5.8, but we define it for
> ```

`-- | 'mapTake' is 'Data.Map.take' ...`

---

*[src/tox/Network/Tox/DHT/ClientList.lhs, line 130 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7Q1zuRh2FOoDXdr3w:-Kb7Q1zuRh2FOoDXdr3x:b-ealz1r) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/ClientList.lhs#L130)):*
> ```lhaskell
> 
> instance Arbitrary ClientList where
>   arbitrary = do
> ```

This is an Applicative do: `arbitrary = genClientList <$> arbitrary <*> arbitrarySizedNatural`.

---

*[src/tox/Network/Tox/DHT/DhtState.lhs, line 76 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7Yvf1Nqxq5kq--lsv:-Kb7Yvf1Nqxq5kq--lsw:b-niqze5) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/DhtState.lhs#L76)):*
> ```lhaskell
> 
> The maximum size of the Client List is set to 8.
> (Must be the same or smaller than the bucket size of the close list to make
> ```

Is this "must" enforced? What happens if it's smaller? Is there a test that shows the effects?

---

*[src/tox/Network/Tox/DHT/DhtState.lhs, line 195 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7RFgRO9lRaE7C6_Hd:-Kb7RFgRO9lRaE7C6_He:bratju8) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/DhtState.lhs#L195)):*
> ```lhaskell
>   where
>     addUnlessBase clientList |
>       NodeInfo.publicKey nodeInfo == ClientList.baseKey clientList =
> ```

Put `|` on the same line as the condition, and use `otherwise` for the second case.

---

*[src/tox/Network/Tox/DHT/DhtState.lhs, line 213 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7Z5bi0-ebX6wr_Bef:-Kb7Z5bi0-ebX6wr_Beg:b5a8one) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/DhtState.lhs#L213)):*
> ```lhaskell
> mapSearchClientLists :: (ClientList -> ClientList) -> DhtState -> DhtState
> mapSearchClientLists f =
>     mapSearchEntry $ \entry@DhtSearchEntry{searchClientList} ->
> ```

Add spaces around braces.

---

*[src/tox/Network/Tox/DHT/KBuckets.lhs, line 174 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7Z_qQYdKPNxy9ZiYn:-Kb7Z_qQYdKPNxy9ZiYo:b-f8awhq) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/KBuckets.lhs#L174)):*
> ```lhaskell
> 
> foldNodes :: (a -> NodeInfo -> a) -> a -> KBuckets -> a
> foldNodes f x = foldl f x
> ```

I have mixed feelings about having part of the function body on the same line as the name binding.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hs-toxcore/121)*

**Comment by iphydf** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hs-toxcore/121)*

**Comment by zugz** [comment]
Review status: 6 of 11 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[src/testsuite/Network/Tox/DHT/ClientListSpec.hs, line 27 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7Ttmuiw5XA9pa0CpF:-KbBfSCtSFLCGzrgrIrS:b-6606ti) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/ClientListSpec.hs#L27)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Indentation is 2 spaces. We can talk about changing that, but then we should change it everywhere at once, in a separate PR.
</blockquote></details>

2 is fine - I just forgot to set softtabstop. Done.

---

*[src/testsuite/Network/Tox/DHT/ClientListSpec.hs, line 57 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7TyyLC5EvPL4zbZHB:-KbBfbSl0HzCRIgl-Fma:b-896fix) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/ClientListSpec.hs#L57)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Unindent by 2 spaces.
</blockquote></details>

Done.

---

*[src/testsuite/Network/Tox/DHT/KBucketsSpec.hs, line 72 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7WSOdEIHBY9W9jMKY:-KbBfkhsXW0Hm5Q_Co6b:b87w8fz) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/KBucketsSpec.hs#L72)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

"it buckets have maximum size" isn't a sentence. I've been trying to keep these tests in the \*spec style with "describe foo: it does bleh, it has blah, it is bork". In this case, you're describing two properties of "buckets": they "have max.." and "have base key...".
</blockquote></details>

OK, rewritten.

---

*[src/testsuite/Network/Tox/DHT/KBucketsSpec.hs, line 74 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7WopHOxWuJcr-H4pU:-KbBfpU0JGK1FrdZraT5:bku3t0c) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/KBucketsSpec.hs#L74)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Add space after `==`. I almost always avoid contracting token sequences. In this case, it hints that `==` and `KBuckets.bucketSize` are more tightly connected than the following `kBuckets`, while actually you're doing `(== (KBuckets.bucketSize kBuckets))`, making this contraction actively confusing.
</blockquote></details>

Agreed. But I combined the two tests, and now it isn't relevant.

---

*[src/testsuite/Network/Tox/DHT/KBucketsSpec.hs, line 78 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7XIba9QVdZ9jTPwzD:-KbBgF7SUjzd7rfaUnKn:b-abr0w3) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/KBucketsSpec.hs#L78)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

I've switched from the `foo $ bar $ cow x` style to `foo . bar . cow $ x` style for two reasons:
1. It makes it clearer that we're applying a composition of functions to some value.
2. Factoring out that composition and giving it a name becomes a matter of just cut&paste instead of cut&paste and then replacing `$` with `.`.

In this particular case, as well as the previous and the next, changing it to composition rather than application also allows for eta-reduction, making it a beautiful `property $ some . function . composition`.
</blockquote></details>

I think it's ok to break this sometimes, but generally I agree. The eta-reduction doesn't actually work here though, because kBuckets is used multiply.

---

*[src/testsuite/Network/Tox/DHT/KBucketsSpec.hs, line 120 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7YSc2VUWK-D09rtN6:-KbBghHvIxOLnwtI_icA:b-voa539) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/KBucketsSpec.hs#L120)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

I'm a bit unhappy about this `O(n^2)` algorithm. It's mine, but perhaps change it to `O(n)` if it doesn't become too ugly? Also in the other test you copied from this one.
</blockquote></details>

Done, using reverse. Unless you see a neater solution?

---

*[src/tox/Network/Tox/DHT/ClientList.lhs, line 54 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7QSGfOPwcTW6L6L1q:-KbBgpplpV_MfX4Rn40J:b-pbdqz3) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/ClientList.lhs#L54)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Align `=` and put `}` on a separate line (makes it easier to reorder bindings).
</blockquote></details>

Agreed.

---

*[src/tox/Network/Tox/DHT/ClientList.lhs, line 101 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7QrpDYq3a84FVUcSk:-KbBgsNDRP12EjfhIrS2:b-896fix) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/ClientList.lhs#L101)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

`-- | 'mapTake' is 'Data.Map.take' ...`
</blockquote></details>

Done.

---

*[src/tox/Network/Tox/DHT/ClientList.lhs, line 130 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7Q1zuRh2FOoDXdr3w:-KbBh0UmwIIxguX-PLHy:b-zin2r) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/ClientList.lhs#L130)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

This is an Applicative do: `arbitrary = genClientList <$> arbitrary <*> arbitrarySizedNatural`.
</blockquote></details>

That isn't right, genClientList is a -> b -> m c, not a -> b -> c. I couldn't see a neat way to one-line it. Gen does have a Monad instance, so using do should be compatible with older ghc versions.

---

*[src/tox/Network/Tox/DHT/DhtState.lhs, line 76 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7Yvf1Nqxq5kq--lsv:-KbBheGRKWR8l4zNvTLn:bzha59) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/DhtState.lhs#L76)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Is this "must" enforced? What happens if it's smaller? Is there a test that shows the effects?
</blockquote></details>

I don't really know what this comment is talking about, so I thought it best to preserve it as it was.

---

*[src/tox/Network/Tox/DHT/DhtState.lhs, line 195 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7RFgRO9lRaE7C6_Hd:-KbBhoAcPQPCVYbotc8q:bwif6a0) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/DhtState.lhs#L195)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Put `|` on the same line as the condition, and use `otherwise` for the second case.
</blockquote></details>

not sure I agree with the newline placement, but done anyway. hlint doesn't like using | otherwise here.

---

*[src/tox/Network/Tox/DHT/DhtState.lhs, line 213 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7Z5bi0-ebX6wr_Bef:-KbBhy88drVLT4k4YHfK:bk59f50) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/DhtState.lhs#L213)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Add spaces around braces.
</blockquote></details>

done (here and elsewhere) for consistency, though I'm not sure whether I really prefer it.

---

*[src/tox/Network/Tox/DHT/KBuckets.lhs, line 174 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7Z_qQYdKPNxy9ZiYn:-KbBiGcsulwIvuHzAC9j:b-ikfpie) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/KBuckets.lhs#L174)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

I have mixed feelings about having part of the function body on the same line as the name binding.
</blockquote></details>

I think it's fine if it ends with '$' or 'do' or similar, but if it can be misread as a one-liner, as here, then I agree it's bad.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hs-toxcore/121)*

**Comment by iphydf** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/testsuite/Network/Tox/DHT/KBucketsSpec.hs, line 74 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7WopHOxWuJcr-H4pU:-KbFZFTN63aE-koAGcLq:bkejqif) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/KBucketsSpec.hs#L74)):*
<details><summary><i>Previously, zugz (zugz) wrote…</i></summary><blockquote>

Agreed. But I combined the two tests, and now it isn't relevant.
</blockquote></details>

What about:
```haskell
describe "bucket list" $ do
  it "has maximum size bucketSize" $
    property ..
  it "has the same base key in every bucket" $
    property ..
```

---

*[src/testsuite/Network/Tox/DHT/KBucketsSpec.hs, line 120 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7YSc2VUWK-D09rtN6:-KbFZn92rQ0xIz_XiXDi:brinvtq) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/KBucketsSpec.hs#L120)):*
<details><summary><i>Previously, zugz (zugz) wrote…</i></summary><blockquote>

Done, using reverse. Unless you see a neater solution?
</blockquote></details>

This is fine, thanks.

---

*[src/tox/Network/Tox/DHT/ClientList.lhs, line 130 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7Q1zuRh2FOoDXdr3w:-KbFZsx4LbkTRMifvMSq:b-b9kzu2) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/ClientList.lhs#L130)):*
<details><summary><i>Previously, zugz (zugz) wrote…</i></summary><blockquote>

That isn't right, genClientList is a -> b -> m c, not a -> b -> c. I couldn't see a neat way to one-line it. Gen does have a Monad instance, so using do should be compatible with older ghc versions.
</blockquote></details>

Ah yes, you're right. One option would be `join $ genClientList <$> arbitrary <*> arbitrarySizedNatural`. I'm ok with either.

---

*[src/tox/Network/Tox/DHT/DhtState.lhs, line 195 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7RFgRO9lRaE7C6_Hd:-KbFan5XpGU4Xx4JvU-C:bhfxlli) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/DhtState.lhs#L195)):*
<details><summary><i>Previously, zugz (zugz) wrote…</i></summary><blockquote>

not sure I agree with the newline placement, but done anyway. hlint doesn't like using | otherwise here.
</blockquote></details>

What does hlint say about this? My version (1.9.21) doesn't complain about it:
```haskell
addUnlessBase clientList
  | NodeInfo.publicKey nodeInfo == ClientList.baseKey clientList =
      clientList
  | otherwise = ClientList.addNode nodeInfo clientList
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hs-toxcore/121)*

**Comment by iphydf** [comment]
:lgtm_strong: I'm generally happy with this. You can choose to act on or ignore the remaining comments. Let me know how you choose to proceed, so I can merge when you're happy with it.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-:-KbFoVxsWdqlpGodr6Jo:b-e3xkzx)*

**Comment by zugz** [comment]
Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/testsuite/Network/Tox/DHT/KBucketsSpec.hs, line 74 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7WopHOxWuJcr-H4pU:-KbGrkR-p8Yzc0NUu-oo:b-hvpmmb) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/testsuite/Network/Tox/DHT/KBucketsSpec.hs#L74)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

What about:
```haskell
describe "bucket list" $ do
  it "has maximum size bucketSize" $
    property ..
  it "has the same base key in every bucket" $
    property ..
```
</blockquote></details>

Done. (I made it "every bucket list" for clarity.)

---

*[src/tox/Network/Tox/DHT/ClientList.lhs, line 130 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7Q1zuRh2FOoDXdr3w:-KbGrhhes1msk5uyMH62:b-896fix) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/ClientList.lhs#L130)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Ah yes, you're right. One option would be `join $ genClientList <$> arbitrary <*> arbitrarySizedNatural`. I'm ok with either.
</blockquote></details>

Done.

---

*[src/tox/Network/Tox/DHT/DhtState.lhs, line 195 at r1](https://reviewable.io:443/reviews/toktok/hs-toxcore/121#-Kb7RFgRO9lRaE7C6_Hd:-KbGrTSFtX4fpBXtHFZL:bb5ugcq) ([raw file](https://github.com/toktok/hs-toxcore/blob/e50148d51573cf98d4fbc92f695a2b9ac47c4be2/src/tox/Network/Tox/DHT/DhtState.lhs#L195)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

What does hlint say about this? My version (1.9.21) doesn't complain about it:
```haskell
addUnlessBase clientList
  | NodeInfo.publicKey nodeInfo == ClientList.baseKey clientList =
      clientList
  | otherwise = ClientList.addNode nodeInfo clientList
```
</blockquote></details>

hlint 1.9.32 tells me:
src/tox/Network/Tox/DHT/DhtState.lhs:198:5: Suggestion: Redundant guard
Found:
  addUnlessBase clientList
    | otherwise = ClientList.addNode nodeInfo clientList
Why not:
  addUnlessBase clientList = ClientList.addNode nodeInfo clientList

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hs-toxcore/121)*

**Pull request merged**
